### Transforming code into idioatic python 
- replace traditional index manipulation with python core looping idiomatic

In [1]:
# looping over a range of numbers
for i in [0,1,2,3,4,5]:
    print(i**2,end="  ")

0  1  4  9  16  25  

In [3]:
# idiomatic programming
for i in range(6):
    print(i**2,end="  ")

0  1  4  9  16  25  

### looping over a collection 

In [4]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end="  ")

red  green  yellow  purple  

In [5]:
for color in colors:
    print(color,end="  ")

red  green  yellow  purple  

### looping backwards

In [6]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end="  ")

purple  yellow  green  red  

In [7]:
for color in reversed(colors):
    print(color,end="  ")

purple  yellow  green  red  

### looping in sorted list


In [8]:
colors =['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

In [9]:
colors =['red','green','yellow','purple']
for color in sorted(colors):
    print(color,end=" ")

green purple red yellow 

###
- if x<=y and y<=z:
- if x<=y<=z:
- if x==true:
- if x:

### Pandas

In [10]:
import pandas as pd

In [11]:
dt = {'Id':[11,12,13,14,15],
     'first name':['A','B','C','D','E'],
     'company':['aa','bb','cc','dd','ee'],
     'address':['hyd','hyd','hyd','hyd','hyd']}
mydt = pd.DataFrame(dt)

In [12]:
print(mydt)

   Id first name company address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [16]:
import os


In [21]:
os.chdir("D:\\MyData\\") # saves the certain location

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\MyData\\'

In [20]:
mydt.to_csv('WorkingFile.csv',index=False)

### Reading the data from csv file


In [22]:
mydata=pd.read_csv('WorkingFile.csv')

In [23]:
print(mydata)

   Id first name company address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [24]:
mydata1=pd.read_csv('WorkingFile.csv',skiprows=[1,2,3],
                  names=["CustId","Name","Company","Address"])


In [25]:
print(mydata1)

  CustId        Name  Company  Address
0     Id  first name  company  address
1     14           D       dd      hyd
2     15           E       ee      hyd


In [26]:
pwd


'C:\\Users\\Sai Maheswar\\python'

### print only two columns
### print the large value from custid column max
### least value
### average

In [27]:
d={'first_name':['A','B','C','D','E'],
'CustId':[11,12,13,14,15]}
myData = pd.DataFrame(d)  
print(myData)
CustId=[11,12,13,14,15]
print("Max of Customer Id:",max(CustId))
print("Min of Customer Id:",min(CustId))
print("Average of Customer Id:",sum(CustId)/len(CustId))

  first_name  CustId
0          A      11
1          B      12
2          C      13
3          D      14
4          E      15
Max of Customer Id: 15
Min of Customer Id: 11
Average of Customer Id: 13.0


### Numpy - working with  multidimensional array
- Numpy arrays is a bit like python list
- Numpy array is data structure of Numpy lib
- Its short name for numeric python or numerical python

In [28]:
import numpy as np

In [29]:
li = [1,2,3,4,5]
print(li,end="  ")

[1, 2, 3, 4, 5]  

In [30]:
array = np.array(li)
print(array)

[1 2 3 4 5]


In [33]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [34]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))


[[1 2 3]
 [4 5 6]]
